Blueshield Rearmament
Fluffy-Frontier/Fluffy-STG pull request #9
Opened 2023-04-18 06:30 UTC by HWSensum

## About The Pull Request

Данный ПР добавляет для БЩ эксклюзивное оружие, Револьвер SR-8.
Данный энергетический револьвер стреляет особыми одноразовыми энергетическими капсулами, которых существует 3 вида: 
1) S-Shots - они же не-летальные боеприпасы работающие по принципу дизейблера.
2) Basic Laser - представляет собой боеприпас, который заставляет револьвер выпускать весьма привычные лазеры.
3) E-Bullets - особые капсулы, которые заставляют револьвер выпускать концентрированный сгусток энергии, который по своим баллистическим и поражающим свойствам идентичен пуле.

Данные боеприпасы нельзя напечатать на верстаке, нельзя напечатать на техфабах, а можно только заказать, причём лишь только в разделе "личных" товаров.

Боеприпасы поставляются в специальных "спидлоудерах", которые по некой причине были сильно конструктивно усложнены, из-за чего они стали более громоздкими (на деле фича чтобы не пихали кучу клипс по коробкам).

## How This Contributes To The Skyrat Roleplay Experience

На ФФ появится новое, уникальное оружие, которое разнообразит снаряжение БЩ. Также сверху к этому БЩ будет иметь в ящике обычные боевые перчатки, на случай если ему не нравится трейт tackler (дефолтные перчатки БЩ точно такие же по статам, просто имеют сверху трейт на захваты).

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://user-images.githubusercontent.com/121913313/232690312-9c614cba-6328-4067-a94d-cbb63b85b48e.mp4

</details>

## Changelog

:cl:
add: Added new weapon: SR-8
add: Energy capsules ammo.
qol:  Gave blueshield combat gloves, in case if he doesn't want to tackle people.
code: Holsters now have "badass" var that turns on or off gun_flip trait.
/:cl:

2023-04-18 07:12 UTC, HWSensum commented
Что-то с тестами

2023-04-18 07:29 UTC, FeenieRU commented
![image](https://user-images.githubusercontent.com/62373791/232703925-edfa24c2-b400-4b56-a948-cee19d9aa633.png)

2023-04-18 07:41 UTC, HWSensum commented
Сейчас, в общем, попробую исправить, но там часть проблем из-за костыля, который я вынужден использовать ибо крысы криворукие.

2023-04-18 08:36 UTC, HWSensum commented
Я изменил свой костыль, сейчас он не должен при создании создавать рантаймы.

2023-04-18 09:01 UTC, HWSensum commented
В общем, к чёрту эти костыли, лучше потом нормально пофикшу переменную у пулек, чтобы их печатать было нельзя.

2023-04-18 09:03 UTC, Kush1Push1 commented
Ошибки в тестах к этому ПР не относятся

2023-04-18 09:05 UTC, Kush1Push1 commented
Вроде норм

2023-04-18 09:19 UTC, HWSensum commented
Там была пара ошибок в тестах, которые вызваны были моим костылём. Сейчас ошибки вызванные моим ПРом я исправил.

2023-04-23 19:45 UTC, sasichkamega requested changes

2023-04-23 19:45 UTC, sasichkamega commented on code/game/objects/items/storage/holsters.dm
> +		// FLUFFY FRONTIER EDIT END
Будет лучше восприниматься, если BEDIN и AND Будет на одном уровне.

```dm
	// FLUFFY FRONTIER EDIT BEGIN
	// ORIGINAL LINE: if(slot & (ITEM_SLOT_BELT|ITEM_SLOT_SUITSTORE))
	if(badass && slot & (ITEM_SLOT_BELT|ITEM_SLOT_SUITSTORE))
	// FLUFFY FRONTIER EDIT END
```

2023-04-24 14:37 UTC, FeenieRU commented
Так и не увидел исполненных правок по уменьшению дамага баллистического заряда, что потребовали сделать

2023-04-27 13:04 UTC, HWSensum commented
> Так и не увидел исполненных правок по уменьшению дамага баллистического заряда, что потребовали сделать

Нет, дамаг педали утвердили оставить таким, какой он есть. Единственное что под изменения пошло - введение возможности печатать боеприпасы в верстаке, это тоже было утверждено педалями.

2023-04-27 13:04 UTC, HWSensum commented on code/game/objects/items/storage/holsters.dm
> +	var/badass = TRUE
Исправлено.

2023-04-27 13:05 UTC, HWSensum commented on code/game/objects/items/storage/holsters.dm
> +		// FLUFFY FRONTIER EDIT END
Исправлено.

2023-04-27 19:29 UTC, merged